# Generated by Django 4.2.5 on 2023-09-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='fechaEntrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
